### ISSUE TITLE
Anthropic API key not detected from .env file

### ISSUE THREAD

**Issue by Gyurmatag** [andytyler/playwright-ai#5]
Hello guys!

I added a .env file and added my ANTHROPIC_API_KEY just like that:
`ANTHROPIC_API_KEY="my_api_key"`

But I have an error when calling the ai function:

```
Error: Could not resolve authentication method. Expected either apiKey or authToken to be set. Or for one of the "X-Api-Key" or "Authorization" headers to be explicitly omitted

    at Anthropic.validateHeaders (/Users/gyuri/Desktop/intro/node_modules/@anthropic-ai/sdk/src/index.ts:236:11)
    at Anthropic.buildHeaders (/Users/gyuri/Desktop/intro/node_modules/@anthropic-ai/sdk/src/core.ts:378:10)
    at Anthropic.buildRequest (/Users/gyuri/Desktop/intro/node_modules/@anthropic-ai/sdk/src/core.ts:328:29)
    at Anthropic.makeRequest (/Users/gyuri/Desktop/intro/node_modules/@anthropic-ai/sdk/src/core.ts:436:40)
    at callAnthropicComputerUse (/Users/gyuri/Desktop/intro/node_modules/tests-ai/src/anthropic-call.ts:11:20)
    at runTest (/Users/gyuri/Desktop/intro/node_modules/tests-ai/src/index.ts:86:24)
    at ai (/Users/gyuri/Desktop/intro/node_modules/tests-ai/src/index.ts:8:15)
    at /Users/gyuri/Desktop/intro/tests/example.spec.ts:6:3
```

I have this folder structure:

![Képernyőfotó 2024-11-25 - 21 59 02](https://github.com/user-attachments/assets/4baf93b3-0d0f-47e9-82e8-e6e81b8f5e77)

Please fix this error, because it is blocking us to try this!

Thank you very much!

**Comment by olivier-martin-sf** [comment]
The library doesn't load your `.env` file automatically. You will need to make sure that your env file is loaded before. You can see examples in the playwright configuration in the repo:

https://github.com/andytyler/playwright-ai/blob/575dfdf0323f0d0a4600d110de8f560de56cbee7/apps/svelte-example/playwright.config.ts#L2-L6

**Comment by aditya-qapitol** [comment]
I used the following to make it work
```
require('dotenv').config();
import { config } from "dotenv";
```

**Comment by Gyurmatag** [comment]
Okay, now it works. Probably you should include this in the readme. Thank you!
